# Generated by Django 4.2 on 2026-06-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_artigo_texto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artigo',
            table='artigo',
        ),
    ]
